name: dgen # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.33' # just for humans, typically '1.2+git' or '1.3.2'
summary: The Sega console emulator dGen
description: |
  The Sega console emulator dGen

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  dgen_icon.png
title: dGen

apps:
  dgen-linux:
    command: dgen
  dgen-tobin:
    command: dgen_tobin
parts:
  dgen:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      dgen: build/
      dgen.1: man/man1/

architectures:
  - build-on: amd64

